# Generated by Django 5.2.5 on 2025-08-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва авіакомпанії')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='IATA код')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Авіакомпанія',
                'verbose_name_plural': 'Авіакомпанії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='IATA код')),
                ('name', models.CharField(max_length=200, verbose_name='Назва аеропорту')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Аеропорт',
                'verbose_name_plural': 'Аеропорти',
                'ordering': ['city', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('nationality', models.CharField(max_length=50, verbose_name='Громодянство')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пасажир',
                'verbose_name_plural': 'Пасажири',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Номер рейсу')),
                ('departure_time', models.DateTimeField(verbose_name='Час відправлення')),
                ('arrival_time', models.DateTimeField(verbose_name='Час прибуття')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип літака')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базова ціна')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airline', verbose_name='Авіакомпанія')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='booking.airport', verbose_name='Прибуття')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='booking.airport', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейси',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронювання')),
                ('seat_number', models.CharField(max_length=10, verbose_name='Номер місця')),
                ('travel_class', models.CharField(choices=[('Business', 'Бізнес'), ('Economy', 'Економ'), ('First', 'Перший клас')], default='Economy', max_length=20, verbose_name='Клас подорожі')),
                ('status', models.CharField(choices=[('Booked', 'Заброньовано'), ('Checked-in', 'Реєстрація завершена'), ('Cancelled', 'Скасовано')], default='Booked', max_length=20, verbose_name='Статус')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passenger', verbose_name='Пасажир')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплати')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума оплати')),
                ('method', models.CharField(choices=[('Card', 'Карта'), ('PayPal', 'PayPal'), ('Cash', 'Готівка')], max_length=20, verbose_name='Метод оплати')),
                ('status', models.CharField(choices=[('Paid', 'Оплачено'), ('Pending', 'В очікуванні'), ('Failed', 'Помилка')], default='Pending', max_length=20, verbose_name='Статус')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Номер квитка')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата видачі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Дійсний квиток')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['-issue_date'],
            },
        ),
    ]
